alias lg1="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all"
alias lg2="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)' --all"

# zsh script checks first if there were any commits done
#   by author yesterday. If there were, return those. If
#   there weren't, look for all commits since last Friday
#   at midnight as it may have been a weekend.

gitstandup() {
  NAME=$(git config user.name)
  if [ -z "$(git log --all --pretty=format:'* %s' --no-merges --reverse --author="$NAME" --since=yesterday.midnight)" ]; then
    git log --all --pretty=format:'* %s' --no-merges --reverse --author="$NAME" --since=last.friday.midnight;
  else
    git log --all --pretty=format:'* %s' --no-merges --reverse --author="$NAME" --since=yesterday.midnight;
  fi
}

alias gtsu='gitstandup'

# Gives a menu of existing branches and deletes the selected one localy and remotly
alias gtbd="git branch | fzf | xargs -I % sh -c 'git branch -D %; git push origin :%;'"
