# Debrif Navn_på_fotograf
function Debrif {
  ~/Documents/Scripts/skydive-video-handling/Debrif $1
}

# abapruv abap.abp
function abapruv {
  ~/Documents/ABAP/Scripts/Remove-unused-declarations/Remove_unused_declarations $1
}

function testing {
  ~/Documents/Scripts/Script\ template $1
}

# catpdf all.pdf *.pdf
alias catpdf="/System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py --verbose --output"
alias lg1="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all"
alias lg2="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)' --all"

#Play musix
alias m="~/Documents/Scripts/Musikk/Controle\ Music.sh"

#Send email
function e {
  #!/bin/bash

  if [[ "$1" = "-h" ]]; then
    echo "e body.md to_address [subject]"
    exit
  fi

  if [[ $3 = "" ]]; then
    subject=$(grep -e "#" "$1" | head -n 1 | sed 's/#//g' | sed 's/^ //g')
    if [[ $subject = "" ]]; then
      subject="En liten ting"
    fi
  else
    subject=$3
  fi

  to=$2

  pandoc -s --highlight-style kate -H ~/Documents/Scripts/Email/github-pandoc.css -f markdown -t html "$1" | \
    mutt -e "set content_type=text/html" -s "$subject" $to

}

#Open in Google Chrome
function oigc() {
  open $1 -a "Google Chrome"
}

# Convert markdown to html with syntax highlighting
function mtoh() {
  pandoc -s --highlight-style kate -H ~/Documents/Scripts/Email/github-pandoc.css -f markdown -t html "$1" | pbcopy
}

function server {
  git grep 'resources/sap-ui-core.js' -- '*.html' > .tempfile

  while read line; do

    FILE=$(echo "$line" | sed "s/:.*//") 
    CODE=$(echo "$line" | sed "s/.*://") 

    /usr/bin/open -a "/Applications/Google Chrome.app" "http://localhost:8888/$FILE"
  done < .tempfile

  rm .tempfile

  node static_server.js
}
